@include('_partials.website.header')
<link rel="stylesheet" type="text/css" href="{{asset('css/style.min.css')}}">
<body class="about-us">

    <div class="page-wrapper">
        @include('_partials.website.nav')
        <!-- End Header -->
        <main class="main">
            <nav class="breadcrumb-nav">
                <div class="container">
                    <ul class="breadcrumb">
                        <li><a href="{{url('/') }}"><i class="d-icon-home"></i></a></li>
                        <li>Privacy Policy</li>
                    </ul>
                </div>
            </nav>
            <div class="page-header pl-4 pr-4" style="background-image: url(images/page-header/about-us.jpg)">
                <h1 class="page-title font-weight-bold lh-1 text-white text-capitalize">Privacy Policy</h1>
            </div>
            <div class="page-content mt-10 pt-10">
                <section class="about-section pb-10 appear-animate">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-lg-12 mb-10 mb-lg-4">
                                <h5 class="section-subtitle lh-2 ls-md font-weight-normal">Thank You for visiting www.myupavan.com My Upavan ("Firm") is a proprietary firm and is the owner of the website –www.myupavan.com and all its variants ("Site"). This Privacy Policy ("Policy") contains that how the Firm uses any personal information submitted or collected at the Site with Your consent.</h5>
                                <p class="section-desc">For the purpose of this Policy, wherever the context so requires "You" shall mean any natural or legal person who has accessed the Site and/or agreed to become a buyer on the Site by providing required details.</p>
                                <p class="section-desc">Please read this Policy before using the Site and/or submitting any personal information. By accessing and using the Site and/or various features available and present herein, You accept and confirm Your acceptance to the practices and standard operating procedure as described in this Policy. These practices may be changed at the sole discretion of the Firm, with or without notice, from time to time as part of continuous change and applicability of new business, regulatory, legal and statutory provisions which are binding upon the Firm as a law abiding corporate citizen but any changes which could be undertaken by the Firm shall be published and changes will only be applicable to activities and information on a prospective basis, not retroactively. Please ensure that You read and understand this Policy and the terms and conditions thereof as and when You visit the Site.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Collection of information</h3>
                                <p class="section-desc">This Policy applies to any and all information collected and/or submitted on the Site like e-mail address, name, home or work address or telephone number etc. When You use the Site, Firm receives information which is provided by You from time to time. Firm also receives information about Your interaction with our services, Your advertising preferences and Your communications with the Firm. Firm receives this information when You use the Site, Firm's services, register for an account with the Site, provide the information on a web form, update or add information to Your account, participate in community discussions, chats, dispute resolution, or when You otherwise correspond with the Firm regarding the services. This information comprises the following: Device ID or unique identifier, device type, ID for advertising, unique device token, Geo-location information, including location information from Your mobile device, computer and connection information such as statistics on Your page views, traffic to and from the Site, referral URL, ad data, Your IP address, Your browsing history and Your web log information. Please note that most of the mobile devices allow You to control or disable the use of location services by any application on Your mobile device in the device's settings menu.</p>
                                <p class="section-desc">When You use the Site, Site's servers (which may be hosted by a third party service provider) may collect information indirectly and automatically about Your activities on the Site; for instance by way of cookies. A cookie is a small amount of data that is sent to a user's browser from a web server and is eventually stored on a user's computer hard drive. This anonymous information is maintained distinctly and is not linked to the other information which You Submit. However, whether You want Your web browser to accept cookies or not, is up to You. Please note that if You haven't changed Your computer's settings, most likely Your browser already accepts cookies. If You choose to decline cookies, You may not be able to fully experience all features of the Site. However, You can also delete Your browser cookies or disable them entirely, but this may significantly impact Your experience with the Site and may make sections of the Site non-functional or inaccessible. We suggest to keep the cookies turned on in order to have best experience of the Site.</p>
                                <p class="section-desc">Site also uses third-party service providers to serve advertisements across the Site. These service providers may collect some information about Your visits to our Site and Your interaction with our products and services. However, no personally identifiable information is collected or used in this process.</p>
                                <p class="section-desc">Information collected by the Firm is used solely for the purpose of billing and shipping of Your purchases at the Site. Firm do not receive any information about Your computer hardware, software or payment information. Neither Firm sell/ disclose/ share/ distribute sensitive information to any third party for any purpose except to extent of delivery of products ordered. However if the Firm is obliged to act under a valid judicial, statutory or regulatory order, ruling or judgments to provide Your details, Firm shall undertake its responsibility in that regards in a diligent manner, and shall not be liable to either inform or intimate You prior to formal disclosure to above mentioned authorities. Any claim for damages in a civil suit or in tort, brought or instituted by You against the Firm or its authorized officers, agents, managers or other related personnel shall not held as a valid claim at any point of time. Firm shall not responsible or liable for the privacy statements or other content of other websites which are hosted on Site's home page, and You are suggested to check the veracity and the applicability of the same directly at your own risk.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Use of the information</h3>
                                <p class="section-desc">Firm uses the information which is collected from You and/or which is provided by You while accessing the Site for the sole purpose of providing services to You. In addition to this, Firm may use the same information collected/received for one or more of the following purposes:</p>
                                <ul>
                                	<li>To provide information that You request on the Site relating to the products or services;</li>
                                	<li>To provide information relating to other products that may be of interest to You. Such additional information will only be provided if you have consented to receive such information and the same is available at the time of Your consent;</li>
                                	<li>To inform any changes to the Site, services or goods offered by various vendors;</li>
                                	<li>To personalize Your experience on the Site and Firm's other sites by presenting advertising, products and offers tailored to You;</li>
                                	<li>To improve the services, content and advertising on the Site;</li>
                                	<li>If You purchase any product or avail any service from the Site, then to complete and fulfill Your purchase, for example, to have Your payments processed, communicate to You regarding Your purchase and provide You with related customer service;</li>
                                	<li>For proper administering of the Site;</li>
                                	<li>To address Your problems with the Site including addressing any technical problems, to conduct internal reviews and data analysis for the Site (e.g., to determine the number of visitors to specific pages within the Site);</li>
                                	<li>To protect the integrity of the Site; and</li>
                                	<li>To respond to judicial process and provide information to law enforcement agencies or in connection with an investigation on matters related to public safety, as permitted by law.</li>
                                </ul>
                                <p class="section-desc">If You have previously purchased goods or services from the Site, Firm may provide You details of similar goods or services, or other goods or services that You may be interested in. You can be sure that Firm does not disclose any thing that could be held against or serve as an identification to individuals or to use such classification in a manner which is portrayed by way of race, creed, religion, sex, political and caste. Firm uses return email addresses to answer the email and don't use the same for any other purpose. Firm may use non-identifying information to design the Site and share the same with advertisers.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Access to information</h3>
                                <p class="section-desc">Only authorized employees, service providers, agents and contractors (who have agreed to keep information secure and confidential) may have access to information collected/received by You. All emails and newsletters from the Site allows You to opt out of further mails. Extremely sensitive information like Your credit-card details etc. are transacted upon secured sites of approved payment gateways which are digitally under encryption, thereby providing the highest possible degree of care as per the best technology and industry practice. However, You may use Your discretion while using the services at the Site.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Distribution of Information</h3>
                                <p class="section-desc">Firm may share information with limited third parties like governmental agencies or other companies assisting in fraud prevention or investigation. Firm may do so when: (1) permitted or required by law; or, (2) trying to protect against or prevent actual or potential fraud or unauthorized transactions; or, (3) investigating fraud which has taken place.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Disclosure</h3>
                                <p class="section-desc">Firm may disclose information received or collected from You to other members/affiliates of the Firm or to third parties. This disclosure may be required to provide access to our services, to comply with our legal obligations, to enforce our user agreement, to facilitate our marketing and advertising activities, to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services. Firm try its best endeavor to minimize the amount of information that is disclosed and what is directly relevant and necessary to accomplish the specified purpose. As stated above, Firm strictly do not disclose information to third parties for their marketing and advertising purposes without Your explicit consent.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Links to third party websites</h3>
                                <p class="section-desc">The Site also provides third-party advertisements and links to other websites. However Firm strictly does not provide any personal information to these third-party websites or advertisers.</p>
                                <p class="section-desc">Site may contain links to other websites ("Linked Site") which are operated by third parties and are not controlled by or affiliated to or associated with the Site/Firm, unless expressly specified on the Site. Firm is not responsible for any form of transmission, whatsoever, received by You from any Linked Site. Accordingly, Firm does not make any representations concerning the privacy practices or policies of such third parties or terms of use of such websites, nor does Firm control or guarantee the accuracy, integrity or quality of the information, data, text, software, music, sound, photographs, graphics, videos, messages or other materials available on such Linked Site. The inclusion or exclusion does not imply any endorsement by the Firm of the website, the website's provider or the information on the website. The information provided by You to such Linked Site or third party websites shall be governed in accordance with the privacy policies of such websites, and it is recommended that You review the privacy policy on any such websites prior to using such websites.</p>
                                <p class="section-desc">These Linked Site or third-party websites and advertisers may use technology to send the advertisements that appear on the website directly to Your browser. In such cases, the third party websites or advertisers automatically receive Your IP address. They may also use cookies, JavaScript, web beacons and other technologies to measure the effectiveness of their advertisements and to personalize advertising content. Firm does not have access to or control over cookies or other features that such third party websites and advertisers may use, and the information practices of these third-party websites and advertisers are not covered by this Policy. So You should contact them directly for more information about their privacy practices.</p>
                                <h3 class="section-title lh-1 font-weight-bold mt-10">Terms Used</h3>
                                <p class="section-desc">"We/the Firm/us" terms used in this Policy, terms and conditions or on the Site are interchangeable and shall mean and include as entity referring to My Upavan</p>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End About Section-->
            </div>
        </main>
        <!-- End Main -->
        @include('_partials.website.footer')
        <script src="{{asset('vendor/jquery.count-to/jquery-numerator.min.js')}}"></script>
</body>

</html>